@startuml
title Aktivität: Game Over (core)

start
repeat :GameStage act();
    :GameService.step();
    backward :GameStage.draw();
    label initPoint
repeat while (not game over) is (yes)
->no;
:GameOverScreen.show();
:ScoreboardRepository.addScore();
:ScoreboardRepository.getGameOverScores();
:GameOver.show();
:ScoringService.saveScore();
:ScoringService.getTopTen();
stop
@enduml
