@startuml
title Aktivitätsdiagramm: Game Over Check

start
repeat :GameField act();
    :activeShape.move();
    backward :GameField.render();
    label initPoint
repeat while (successful move & not out of bounds) is (yes)
->no;
:GameOver.show();
:ScoringService.saveScore();
:ScoringService.getTopTen();
stop
@enduml
