@startuml
left to right direction

title Kontextsicht: Tetrix

actor Spieler as Player

rectangle "Benutzer Gerät" as Device {
    rectangle "LibKtx\n(Kotlin Desktop App)" as App {
      [Tetrix]
    }

node "Dateisystem\n(Datei)" as FS
node "Datenbank\n(JDBC)" as DB
}

Player --> App : Eingabe (Rotation,\nBewegung, Menüsteuerung)
App --> Player : Ausgabe (Grafik,\nPunktestand, Statusmeldungen)

App --> FS : Lese/Schreibe\nSpieldaten
App --> DB : Lese/Schreibe\nSpieldaten über JDBC
@enduml
