@startuml
hide footbox
title Laufzeitsicht: Spielstart (core)

actor Spieler as Player
participant Game as G
participant "LoadingScreen" as LS
participant "MainMenuScreen" as MMS
participant "GameScreen" as GS
participant "AssetManager" as AM
participant "ScoreboardScreen" as SBS
participant "OptionMenuScreen" as OMS
participant "GameStage" as GST

Player -> G : create()
activate G
G -> AM ** : init
G -> LS : show()
activate LS
LS -> LS : loadAssets()
Player --> LS : <<interact>>
LS -> MMS : show()
deactivate LS
activate MMS
Player --> MMS : press "Start" button
MMS -> GS : show()
activate GS
GS -> GST ** : init
note over GST
render/update loop
endnote
@enduml
