@startuml
hide footbox
title Laufzeitsicht: Spielstart

actor Spieler as Player
participant Game as G
participant "LoadingScreen" as LS
participant "MenuScreen" as MS
participant "GameScreen" as GS
participant "AssetManager" as AM
participant "ScoreScreen" as SS
participant "OptionsScreen" as OS
participant "GameField" as GF

Player -> G : create()
activate G
G -> LS ** : init
G -> MS ** : init
G -> GS ** : init
G -> AM ** : init
G -> SS  ** : init
G -> OS  ** : init
G -> LS : show()
activate LS
LS -> LS : loadAssets()
Player --> LS : <<interact>>
LS -> MS : show()
deactivate LS
activate MS
Player --> MS : press "Start" button
MS -> GS : show()
activate GS
GS -> GF ** : init
note over GF
game cycle runs
endnote
@enduml
