@startuml
hide footbox
title Eingabe & Bewegung (core)

participant GameStage as GST
participant GameService as Service
participant Shape as Shape
collections Cubes as C

activate GST
loop while (input)
    GST -> Service : move*/rotate*
    activate Service
    Service -> Shape : canMove()/apply()
    activate Shape
    Shape -> C : checkCollisions()
    activate C
    C --> Shape : ok
    deactivate C
    Shape --> Service : updated
    deactivate Shape
    Service --> GST : success
    deactivate Service
end
@enduml
